#!/bin/bash
# Generated by ChatGPT

# Check if nvidia-smi is available
if ! command -v nvidia-smi &> /dev/null; then
    echo "nvidia-smi not found. NVIDIA drivers may not be installed or no NVIDIA GPUs are available."
    exit 1
fi

# Use nvidia-smi to list GPUs and count the number of lines in the output
gpu_count=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)

echo "Number of available GPUs: $gpu_count"
